/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package senai.desafio004;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.intellijthemes.FlatCarbonIJTheme;
import javax.swing.SwingUtilities;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author Aluno
 */
public class InterfaceDesafio extends javax.swing.JFrame {
    
    private LocalTime horaEntrada;
    private LocalTime horaSaida;
    private LocalDate dataEntrada;
    private LocalDate dataSaida;
    private Servico servicoAtual;
    /**
     * Creates new form InterfaceDesafio
     */
    public InterfaceDesafio() {
        initComponents();
        setLocationRelativeTo(null);
        btnSwitch.putClientProperty("btnSwitch.buttonType", "roundRect");
    }
    
    public void limparCampos() {
    txtPlaca.setText("");
    txtModelo.setText("");
    txtPlaca.requestFocus();
    txaTicket.setText("");
    
    }
    
    private void alteraTema(javax.swing.LookAndFeel laf) {
    try {
        UIManager.setLookAndFeel(laf);
        SwingUtilities.updateComponentTreeUI(this);
    } catch (Exception ex) {
        System.out.println("falha ao mudar o tema");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbxServico = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTicket = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        btnEntrada = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        btnSwitch = new javax.swing.JToggleButton();
        btnNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estacionamento Igloo");

        cbxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estacionamento", "Lavagem Simples", "Lavagem Completa" }));
        cbxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxServicoActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lblTitulo.setText("IglooPark");

        jLabel1.setText("Placa :");

        jLabel2.setText("Modelo :");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        jLabel3.setText("Serviços :");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        jLabel4.setText("Entrada :");

        jLabel5.setText("Saida :");

        txaTicket.setColumns(20);
        txaTicket.setRows(5);
        jScrollPane1.setViewportView(txaTicket);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ticket:");

        btnEntrada.setText("Registrar");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSaida.setText("Registrar");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        btnSwitch.setText("💡");
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwitchActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxServico, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaida, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(btnSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnEntrada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnSaida))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxServicoActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        if (txtPlaca.getText().isEmpty() || txtModelo.getText().isEmpty()) {

        JOptionPane.showMessageDialog(
            this,
            "Preencha todos os campos!",
            "Erro",
            JOptionPane.WARNING_MESSAGE
        );

            return;
        }
        
        StringBuilder sb = new StringBuilder();

        sb.append("--     Ticket     -- \n\n");
        sb.append("Placa: " + txtPlaca.getText() + "\n");
        sb.append("Modelo: " + txtModelo.getText() + "\n");
        sb.append("Serviço: " + cbxServico.getSelectedItem()+ "\n");
        String servicoSelecionado = cbxServico.getSelectedItem().toString();
        
        if (servicoSelecionado.equals("Estacionamento")) {

        servicoAtual = new Estacionamento(
                txtPlaca.getText(),
                txtModelo.getText(),
                horaEntrada,
                horaSaida
            );
        } else {

            servicoAtual = new Lavagens(
                    txtPlaca.getText(),
                    txtModelo.getText(),
                    servicoSelecionado
            );
        }
        
        if(horaEntrada == null){
           JOptionPane.showMessageDialog(
                this,
                "Registre a entrada primeiro"
            );
           return;
        }else if(horaSaida == null){
           JOptionPane.showMessageDialog(
                this,
                "Registre a saida"
            );
           return;
        }else if (horaEntrada == null || horaSaida == null) {

            JOptionPane.showMessageDialog(
                this,
                "Registre a entrada e a saida primeiro"
            );

            return;
        }

        LocalTime horaFechada = LocalTime.of(22, 0);

        if (horaSaida.isAfter(horaFechada)) {

            JOptionPane.showMessageDialog(
                this,
                "O " + lblTitulo.getText() + " está fechado depois das 18:00",
                "Aviso",
                JOptionPane.ERROR_MESSAGE
            );

            limparCampos();
            return;
        } else {
            
            DateTimeFormatter formatadordt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String dataFormatadaE = dataEntrada.format(formatadordt);

            DateTimeFormatter formatadorhr = DateTimeFormatter.ofPattern("HH:mm:ss");
            String horaFormatadaE = horaEntrada.format(formatadorhr);

            DateTimeFormatter formatadordts = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String dataFormatadaS = dataSaida.format(formatadordts);

            DateTimeFormatter formatadorhrs = DateTimeFormatter.ofPattern("HH:mm:ss");
            String horaFormatadaS = horaSaida.format(formatadorhrs);
            
            sb.append("Entrada: " + dataFormatadaE + " às " + horaFormatadaE + "\n");
            sb.append("Saída: " + dataFormatadaS + " às " + horaFormatadaS + "\n\n");
        }
        
        sb.append("=================================================\n\n");
        
        double total = servicoAtual.calcularTotal();
        sb.append("Total: R$ " + total);
        
        txaTicket.setText(sb.toString());
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
    
       horaEntrada = LocalTime.now();
       dataEntrada = LocalDate.now();
       
       JOptionPane.showMessageDialog(this, "Entrada registrada!");
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed

        
        if(horaEntrada == null){
           JOptionPane.showMessageDialog(
                this,
                "Registre a entrada primeiro"
            );
           return;
        }
        
        horaSaida = LocalTime.now();
        dataSaida = LocalDate.now();
        
        JOptionPane.showMessageDialog(this, "Saída registrada!");
    }//GEN-LAST:event_btnSaidaActionPerformed

    private void btnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwitchActionPerformed
        if(btnSwitch.isSelected()){
            
            alteraTema(new FlatCarbonIJTheme());
        }else{
            
            alteraTema(new FlatLightLaf());
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSwitchActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
          if (horaEntrada == null || horaSaida == null) {

            JOptionPane.showMessageDialog(
                this,
                "Não há nenhum ticket nesse momento"
            );

            return;
        }
          
        limparCampos();
        
        JOptionPane.showMessageDialog(
            this, 
            "Novo Ticket criado!"
        );
    }//GEN-LAST:event_btnNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDesafio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSaida;
    private javax.swing.JToggleButton btnSwitch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txaTicket;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
